#!/usr/bin/env python3
"""综合摘要补全 - 第五批"""
import glob, os

ABSTRACT_MAP = {
    "10.3389/feduc.2025.1647573": "As generative artificial intelligence (GenAI) continues to generate interest and impact all levels of the educational system, including K-12, it is essential to understand how GenAI has been utilized at the K-12 level. This study explored the literature to understand what GenAI has been used for in K-12 and the reported impacts of its use. By investigating two prominent databases, Scopus and Web of Science, and employing snowballing techniques, this study included 30 papers after a rigorous search and applying inclusion and exclusion criteria. The findings indicate that most existing works focused on high school and preservice teachers. Researchers have explored various subject domains or areas of interest where GenAI has been used, with a significant focus on STEM-related subjects. The quasi-experimental approach emerged as the most commonly used design technique for implementing GenAI ideas in the classroom. Psychological variables were the primary measures used to gauge learning outcomes. This study further aggregates recommendations from prior works and suggests areas for future research.",
    
    "10.3389/feduc.2025.1651217": "As artificial intelligence technologies rapidly enter educational settings, teachers find themselves navigating fundamental pedagogical shifts while maintaining professional agency. Despite growing AI adoption in schools, limited research examines how teachers actually experience and shape AI integration within their classroom contexts, especially in the contexts of developing countries. This study investigates teachers' beliefs about AI's educational role, their incorporation patterns, and associated challenges and opportunities. Using semi-structured interviews with 20 teachers from two private schools in Delhi, India, the paper employed thematic analysis grounded in an AI Literacy and Ecological Teacher Agency Framework. Three key findings emerged: Teachers simultaneously embrace AI's potential to enhance learning and administrative efficiency while expressing deep concerns about student over-dependence and erosion of critical thinking skills. Both teachers and students demonstrate emerging technical AI competencies, but significant gaps in critical evaluation and ethical application remain, revealing a concerning literacy imbalance. Beyond surface-level tool adoption, AI integration fundamentally reshapes teachers' professional beliefs and sense of agency, prompting ongoing renegotiation of their pedagogical identities and classroom authority.",
    
    "10.3389/feduc.2025.1671306": "The rapid integration of artificial intelligence (AI) in education requires teachers to develop AI competencies while preparing students for a society influenced by AI. This study evaluates the impact of an online teacher training program on German in-service teachers' AI literacy, usage behaviors, and attitudes toward AI. A pre-post design study was conducted with teachers (N = 436 for attitude assessment, among whom N = 291 teachers for AI literacy) participating in the course. The program combined synchronous and asynchronous learning formats, including webinars, self-paced modules, and practical projects. The participants exhibited notable improvements across all domains: AI literacy scores increased significantly, and all attitude items regarding AI usage and integration demonstrated significant positive changes. Teachers reported increased confidence in AI integration. Structured teacher training programs effectively enhance AI literacy and foster positive attitudes toward AI in education.",
    
    "10.3390/app15137579": "Multi-agent large language models promise flexible, modular architectures for delivering personalized educational content. Drawing on a pilot randomized controlled trial with middle school students (n = 23), we introduce a two-agent GPT-4 framework in which a Profiler agent infers learner-specific preferences and a Rewrite agent dynamically adapts science passages via an explicit message-passing protocol. We implement structured system and user prompts as inter-agent communication schemas to enable real-time content adaptation. The results of an ordinal logistic regression analysis hinted that students may be more likely to prefer texts aligned with their profile, demonstrating the feasibility of multi-agent system-driven personalization and highlighting the need for additional work to build upon this pilot study. Beyond empirical validation, we present a modular multi-agent architecture detailing agent roles, communication interfaces, and scalability considerations. These results advance both our theoretical and applied understanding of multi-agent LLM systems for personalized learning.",
    
    "10.3390/computers15010049": "Artificial intelligence (AI) is reshaping how learning environments are designed and experienced, offering new possibilities for personalization, creativity, and immersive engagement. This systematic review synthesizes 43 empirical studies (Scopus, Web of Science) to examine the training needs and practices of primary and secondary education teachers for effective AI integration and overall professional development (PD). Following PRISMA guidelines, the review gathers teachers' needs and practices related to AI integration, identifying key themes including training practices, teachers' perceptions and attitudes, ongoing PD programs, multi-level support, AI literacy, and ethical and responsible use. The findings show that technical training alone is not sufficient, and that successful integration of AI requires a combination of pedagogical knowledge, positive attitudes, organizational support, and continuous training. Based on empirical data, a four-level, process-oriented PD framework is proposed, which bridges research with educational practice and offers practical guidance for the design of AI training interventions.",
    
    "10.3390/educsci15091186": "The development of artificial intelligence (AI) has had a significant impact on various sectors, including education. The successful integration of AI tools in classrooms depends largely on teachers' understanding and knowledge, confidence, and training. This study explores how educators in grade 3 to 12 utilize AI tools, their level of confidence employing these tools, and their professional development (PD) needs. It also investigates the challenges educators face integrating AI into their practice. Participants were 242 teachers (79% female). Findings revealed that while most teachers were aware of AI writing tools like ChatGPT, their overall familiarity with and understanding of AI concepts were mixed, with slightly less than half currently using AI tools in their instruction. Secondary teachers consistently showed significantly higher levels of AI knowledge, familiarity, usage, and confidence in AI-related teaching practices compared to their elementary counterparts. The primary PD need identified to boost teacher confidence was professional development workshops.",
    
    "10.3390/educsci16010136": "This study investigates the factors influencing Chinese K-12 teachers' adoption of generative artificial intelligence (GenAI) for instructional purposes by extending the Technology Acceptance Model (TAM) with pedagogical beliefs, perceived intelligence, perceived ethical risks, GenAI anxiety, and demographic moderators. Drawing on a theory-driven framework, survey data were collected from 218 in-service teachers across K-12 schools in China. Eight latent constructs and fourteen hypotheses were tested using structural equation modeling and multi-group analysis. Results show that perceived usefulness and perceived ease of use are the strongest predictors of teachers' intention to adopt GenAI. Constructivist pedagogical beliefs positively predict both perceived usefulness and intention, whereas transmissive beliefs negatively predict intention. Perceived intelligence exerts strong positive effects on perceived usefulness and ease of use but has no direct effect on intention. Perceived ethical risks significantly heighten GenAI anxiety, yet neither directly reduces adoption intention. Gender, teaching stage, and educational background further moderate key relationships.",
    
    "10.3390/educsci16040517": "The pedagogical efficacy of artificial intelligence (AI) technologies in education heavily depends on cultural, technological, and cognitive contexts. The current study discusses the interconnection between AI technologies, learner competencies, and educational outcomes, in addition to the significance of digital and media literacy in secondary foreign language teaching. It employs Hofstede's cultural dimensions theory, the technology acceptance model, and sociocultural learning theory to examine how AI technologies affect learning outcomes of English as a foreign language among Lebanese high school students. One hundred and eighty high school students in Mount Lebanon were given a 20-item survey. The findings indicate that AI technologies significantly enhance student learning outcomes: affective and motivational outcomes (45%), social and collaborative competencies (35%), and English language proficiency (accounting for 43% of variance). Furthermore, these relationships are strongly moderated by digital and media literacy, which increases the beneficial effects of AI on learning outcomes.",
    
    "10.3390/educsci16040531": "Generative AI (GenAI) in education has become a divisive topic. While some teachers view GenAI as a transformative tool, others caution against harms and impacts on teaching and learning. Since the usefulness of a tool depends on the user, how teachers view and use GenAI and their perceptions of its role in teaching and learning may influence its benefits and risks. The study adopts a qualitative approach, interviewing 23 higher education teachers with teaching experience across disciplines. Using the Technological, Pedagogical, and Content Knowledge (TPACK) and sensemaking frameworks to guide and analyse the interviews, a set of opportunities, challenges, and threats associated with integrating GenAI in higher education was identified. Teachers highlighted opportunities, including using GenAI as a study buddy. Concerns were raised about students' overreliance on GenAI, GenAI undermining the teaching and learning process, and issues like undetected plagiarism. The findings suggest a need for professional development to help teachers understand GenAI and how it can be effectively used in teaching.",
    
    "10.3390/mti9080084": "Artificial intelligence (AI) is changing how we teach and learn, generating excitement and concern about its potential to transform education. To contribute to the debate, this systematic literature review examines current research trends (publication year, country of study, publication journal, education level, education field, and AI type), as well as the benefits and challenges of integrating AI into education. This review analyzed 155 peer-reviewed empirical studies published between 2015 and 2025. The review reveals a significant increase in research activity since 2022, reflecting the impact of generative AI tools, such as ChatGPT. Studies highlight a range of benefits, including enhanced learning outcomes, personalized instruction, and increased student motivation. However, there are challenges to overcome, such as students' ethical use of AI, teachers' resistance to using AI systems, and the digital dependency these systems can generate. These findings show AI's potential to enhance education; however, its success depends on careful implementation and collaboration among educators, researchers, and policymakers.",
    
    "10.3390/systems13100840": "Generative AI is reshaping K-12 learning as a multi-agent system in which goals, activities, and roles co-evolve across formal and informal environments. Following PRISMA and appraising quality with MMAT, we synthesize 84 peer-reviewed empirical studies (2020-2025) involving learners aged 3-18. Using Biggs's 3P model as a systems lens and embedding CIMO logic, we code learning objectives, activity designs, AI role paradigms, and outcomes. Seven recurring objectives emerge (language/literacy; STEM; creativity; socioemotional skills; feedback literacy and self-regulation; motivation; AI literacy). Five dominant activity patterns are identified: dialogic tutoring and formative feedback, generative iterative co-creation, project-based problem-solving, simulation/game-based learning, and assessment support. Across studies, AI roles shift from AI-directed to AI-supported/empowered, re-allocating agency among students, teachers, and caregivers via feedback loops. Reported outcomes span three categories: epistemic, practice, and affective/identity, with opportunities of deeper knowledge, improved practice, and stronger engagement, and risks of hallucinations, reduced originality, over-reliance, motivational loss, and ethical concerns.",
    
    "10.3991/ijet.v20i04.57879": "This pilot study explores the feasibility of integrating large language model (LLM) assistants into physics education through a Moodle plugin designed to address conceptual understanding in Newtonian mechanics. Using OpenAI's GPT for real-time Socratic dialogue, the plugin guides students through misconception-targeted questions adapted from the Force Concept Inventory (FCI). Aligned with principles of inquiry-based learning, the intervention compares AI-guided feedback with instructor-guided materials over a one-week, three-session classroom study. Results suggest that students receiving AI-guided Socratic dialogue showed greater conceptual gains on certain targeted items (e.g., Newton's Third Law), whereas instructor guidance proved more effective for other concepts (e.g., mass and free-fall independence). Survey feedback highlights the immediacy and interactive nature of the AI while also noting a preference for the clarity provided by instructors. Qualitative analysis suggests that AI-driven dialogue promotes deeper reasoning when restating student ideas and scaffolding reflection. These preliminary findings underscore the potential of LLMs to support conceptual change in physics education when thoughtfully embedded within learning management systems.",
    
    "10.1111/bjet.70055": "With the increasing application of GenAI in education, researchers and practitioners are paying more and more attention to its effectiveness and impact in teaching and learning. This can be evidenced by the increasing number of literature reviews on this topic published in recent years. However, these literature reviews seldom analysed the effectiveness of GenAI-powered educational applications from the human-AI interaction perspective. In response, this study systematically reviews 56 empirical studies on the application of GenAI in education. To explicitly address this gap from the human-AI interaction perspective, the study analyses reviewed studies using the AIED-HCD framework, which conceptualizes three human-AI interaction modes along the dimensions of human control and AI automation, and examined educational contextual factors and educational tasks supported by GenAI to assess how interaction modes vary across teaching and learning contexts. In addition, sensitivity analysis reveals that many studies lack sufficient detail in their statistical reporting, and the reported effect sizes often fall below the thresholds required for acceptable statistical power. The study demonstrates that the mode characterized by both high human control and high AI automation has begun to emerge as a trend, demonstrating promising potential for integrating the respective strengths of humans and AI.",
}

files = glob.glob('/workspace/knowledge/原文库/*.md')
updated = []
for name, abstract in ABSTRACT_MAP.items():
    for f in files:
        with open(f, 'r', encoding='utf-8') as fh:
            content = fh.read()
        if name in content:
            if '## 摘要' in content:
                break
            section = "\n## 摘要\n" + abstract + "\n\n**摘要状态**：✅已补充\n"
            if '## 基本信息' in content:
                content = content.replace('## 基本信息', '## 基本信息' + section, 1)
            else:
                content = content + section
            with open(f, 'w', encoding='utf-8') as fh:
                fh.write(content)
            updated.append(os.path.basename(f))
            break

print("Updated:", len(updated))
for x in updated:
    print("  ✅", x)
