#!/usr/bin/env python3
"""arXiv摘要补全 - 第三批"""
import glob, os

ABSTRACT_MAP = {
    "10.48550/arXiv.2602.16890": "The introduction of generative artificial intelligence applications to the public has led to heated discussions about its potential impacts and risks for K-12 education. One particular challenge has been to decide what students should learn about AI, and how this relates to computational thinking, which has served as an umbrella for promoting and introducing computing education in schools. In this paper, we situate in which ways we should expand computational thinking to include artificial intelligence and machine learning technologies. Furthermore, we discuss how these efforts can be informed by lessons learned from the last decade in designing instructional programs, integrating computing with other subjects, and addressing issues of algorithmic bias and justice in teaching computing in schools.",
    
    "10.48550/arXiv.2602.16894": "In response to the exponential growth in the use of artificial intelligence and machine learning applications, educators, researchers and policymakers have taken steps to integrate artificial intelligence applications into K-12 education. Among these efforts, one equally important approach has received little, if any attention: What if students and teachers were not just learning to be competent users of AI but also its creators? This question is at the heart of CreateAI in which K12 educators, researchers, and learning scientists addressed the following questions: (1) What tools, skills, and knowledge will empower students and teachers to build their own AI/ML applications? (2) How can we integrate these approaches into classrooms? and (3) What new possibilities for learning emerge when students and teachers become innovators and creators? In the report we provide recommendations for what tools designed for creating AI/ML applications should address in terms of design features, and learner progression in investigations. We outline how we need to develop a better understanding of learning practices and funds of knowledge to support youth as they create and evaluate AI/ML applications. This also includes engaging youth in learning about ethics and critically that is authentic, empowering, and relevant throughout the design process.",
    
    "10.48550/arXiv.2603.11709": "While scaling laws for Large Language Models (LLMs) have been extensively studied along dimensions of model parameters, training data, and compute, the scaling behavior of LLM-based educational agents remains unexplored. We propose that educational agent capability scales not merely with the underlying model size, but through structured dimensions that we collectively term the Agent Scaling Law: role definition clarity, skill depth, tool completeness, runtime capability, and educator expertise injection. Central to this framework is AgentProfile, a structured JSON-based specification that serves as the mechanism enabling systematic capability growth of educational agents. We present EduClaw, a profile-driven multi-agent platform that operationalizes this scaling law, demonstrating its effectiveness through the construction and deployment of 330+ educational agent profiles encompassing 1,100+ skill modules across K-12 subjects. Our empirical observations suggest that educational agent performance scales predictably with profile structural richness.",
    
    "10.48550/arXiv.2603.22588": "Teachers face growing pressure to integrate AI tools into their classrooms, yet are rarely positioned as agentic decision-makers in this process. Understanding the criteria teachers use to evaluate AI tools, and the conditions that support such reasoning, is essential for responsible AI integration. We address this gap through a two-day national summit in which 61 U.S. K-12 mathematics educators developed personal rubrics for evaluating AI classroom tools. The summit was designed to support deliberative sensemaking, a process we conceptualize by integrating Technological Pedagogical Content Knowledge (TPACK) with deliberative agency. Teachers generated over 200 criteria - initial articulations spanning four higher-order themes (Practical, Equitable, Flexible, and Rigorous) - that addressed both AI outputs and the process of using AI. Criteria contained productive tensions (e.g., personalization versus fairness, adaptability versus efficiency), and the vast majority framed AI as an assistant rather than a coaching tool for professional learning. Analysis of surveys, interviews, and summit discussions revealed five mechanisms supporting deliberative sensemaking: time and space for deliberation, artifact-centered sensemaking, collaborative reflection through diverse viewpoints, knowledge-building, and psychological safety.",
    
    "10.48550/arXiv.2603.26004": "National and international policy efforts increasingly promote AI literacy in K-12 education, yet access to AI tools alone is insufficient to ensure equitable and responsible participation, particularly in under-resourced contexts. Without designs that integrate ethical reasoning, human support, and opportunities for judgment, AI initiatives risk reinforcing inequities and preparing students to use powerful technologies without critically evaluating their societal consequences. To address this gap, we developed a human-centered, college credit-bearing course on Responsible and Ethical AI for students attending Title I and Title I-eligible high schools, implemented in partnership with the National Education Opportunity Network (NEON). The bichronous course integrates foundational AI concepts with ethical and socio-technical reasoning through asynchronous instruction, near-peer mentorship, and synchronous, discussion-based instruction. In its inaugural year, nearly 180 students from 12 U.S. schools completed the course, with a 97.8% completion rate. Results indicate that students were challenged to apply learning and reason about ethical tradeoffs, while educators reported high engagement, rigor, and meaningfulness relative to typical high school coursework.",
    
    "10.48550/arXiv.2604.01396": "As AI becomes more common in students' everyday experiences, a major challenge for K-12 AI education is designing learning experiences that can be meaningfully integrated into existing subject-area instruction. This paper presents the design and implementation of an AI4K12-aligned curriculum that embeds AI learning goals within a rural middle school science classroom using Breadth-First Search (BFS) as an accessible entry point to AI problem-solving. Through unplugged activities and an interactive simulation environment, students learned BFS as a strategy for exploring networks and identifying shortest paths, then applied it to science contexts involving virus spread and contact tracing. Results suggest that students engaged productively with the curriculum, improved their understanding of BFS and AI problem-solving, and benefited from learning these ideas within ongoing science instruction. Teacher feedback further indicated that the module fit well within the science curriculum while supporting intended science learning outcomes.",
    
    "10.1111/bjet.13563": "To explore the role of parents in secondary school students' persistence in human-AI hybrid learning, this mixed-method study proposes a model that integrates active and restrictive parental mediation into an established baseline model from prior research. Using structural equation modelling to analyse data from 302 students, the proposed model accounted for 66.8% of the variance in continuance intention and 22.9% in continuous learning behaviour. Interestingly, while restrictive mediation was found to be positively correlated with students' continuous learning behaviour, active mediation did not show a significant association with the behaviour. This unexpected finding prompted further investigation through in-depth interviews with 10 students. Thematic analysis revealed that many parents focused on managing online entertainment behaviour. Restrictive mediation, usually implemented through mandatory measures, was found to be more effective in shifting students' attention from entertainment to academic activities. However, many parents lacked sufficient AI literacy and did not receive adequate support from schools and teachers.",
    
    "10.1111/bjet.13595": "Given the significant and unique contributions of both in-class and out-of-class learning, pedagogical initiatives that connect learners' experiences across these two learning spheres would bolster language development. Technology can catalyse the integration. Whether and how teachers utilize this potential of technology to engage in digital bridging initiatives, initiatives that support the connection of students' in-class and out-of-class learning experiences with digital resources, deserve attention. Thematic analysis of 13 interview responses and exploratory and confirmatory factor analyses of 1101 survey responses of primary and secondary school Chinese EFL teachers unravelled two dimensions of digital bridging initiatives: inward bridging practices and outward bridging practices. SEM analysis further revealed various determinants of teachers' bridging initiatives, underscoring the strong and direct influence of teachers' awareness of students' out-of-class digital behaviours and the mediated influence of school culture. The study advocates attention to the nuances of teachers' digital bridging initiatives and influencing factors across contexts.",
    
    "10.1111/ejed.70351": "This study explores the multifaceted impact of Artificial Intelligence (AI) on education, particularly its transformative role in reshaping teacher-student interactions, enhancing personalised learning and contributing to sustainable educational development. As AI technology rapidly advances, its integration in education is driving significant changes in teaching methodologies, student autonomy and the overall educational ecosystem. While AI demonstrates substantial potential to improve learning outcomes through personalised learning paths, intelligent assessments and real-time feedback, it also brings forth several challenges. These include concerns regarding teacher-student dynamics, ethical implications and educational equity. The study reveals that the acceptance and adaptability of both teachers and students play a crucial role in determining AI's effectiveness in the classroom. Teachers' evolving roles, as well as students' increasing autonomy, underscore the need for critical thinking and ethical decision-making skills. However, the research also identifies the risks associated with AI exacerbating existing inequalities, particularly in regions with limited technological access. The findings highlight the necessity of ensuring equitable access to AI resources, especially in disadvantaged areas, and emphasise the importance of comprehensive teacher training to support effective AI integration.",
}

files = glob.glob('/workspace/knowledge/原文库/*.md')
updated = []
for name, abstract in ABSTRACT_MAP.items():
    for f in files:
        with open(f, 'r', encoding='utf-8') as fh:
            content = fh.read()
        if name in content:
            if '## 摘要' in content:
                break
            section = "\n## 摘要\n" + abstract + "\n\n**摘要状态**：✅已补充\n"
            if '## 基本信息' in content:
                content = content.replace('## 基本信息', '## 基本信息' + section, 1)
            else:
                content = content + section
            with open(f, 'w', encoding='utf-8') as fh:
                fh.write(content)
            updated.append(os.path.basename(f))
            break

print("Updated:", len(updated))
for x in updated:
    print("  ✅", x)
